name: json-parser-redcell-sweep

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -V
          python -m pip install -U pip
          python -m pip install -U pytest pytest-cov pytest-html pytest-metadata

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing \
                 --html=pytest-report.html --self-contained-html
        continue-on-error: false

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.html
